name: "✨ Feature Request"
description: Suggest an idea or feature for Algorand Provider
title: "[Feature]: "
labels: ["✨ feature"]
assignees: []

body:
  # welcome
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request, all features are welcome and remember, you're awesome!

  - type: textarea
    attributes:
      label: What is your idea or feature suggestion?
      description: Tell us, what idea or feature you suggest to be added to Algorand Provider.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Benefits
      description: Tell us, how this this will be beneficial to Algorand Provider.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Where can we find information about this?
      description: If you are proposing an integration or third-party plugins, please add relevant links and documentation.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Are you willing to provide a PR to address this?
      options:
        - "Yes"
        - "No"
